### ISSUE TITLE
OpenEye Fix

### ISSUE THREAD

**Issue by WenXin20** [Zeitheron/DarkScriptThemes#17]
This fixes the button on the main menu from [OpenEye](https://minecraft.curseforge.com/projects/openeye). (Which only appears if the game previously crashed.)
```
version 1;
bid a04999a2-01d0-490f-aaa9-3d23081dc561;
id openeye;
name "OpenEye";
description "This fixes the button for OpenEye";
icon "http://dccg.herokuapp.com/cfproject/251457/avatar";
authors ["WenXin2"];
require mod "OpenEye";

#Exclude button from OpenEye
exclude openeye:textures/gui/buttons.png
```

**Comment by Zeitheron** [comment]
![image](https://user-images.githubusercontent.com/38943617/59265834-dd523200-8c4e-11e9-8be8-2ca44c879917.png)

![image](https://user-images.githubusercontent.com/38943617/59266042-5ce00100-8c4f-11e9-9bd1-0fbb8bf4f8f5.png)

**Comment by Zeitheron** [comment]
It seems that I found the issue:

`require mod "openeye";`, `openeye` -> `OpenEye`

For strange reason OpenEye has capital letters in their ModID which shouldn't be the case tbh.

**Comment by Zeitheron** [comment]
Add `bid a04999a2-01d0-490f-aaa9-3d23081dc561;`
