### ISSUE TITLE
OpenComputers compat

### ISSUE THREAD

**Issue by nybry04** [Zeitheron/DarkScriptThemes#2]
This script fix [OpenComputers](https://minecraft.curseforge.com/projects/opencomputers) GUIs.

```
version 1;
bid b1aadf8b-3f88-4d4c-a0f2-a4a77e9b5fce
id opencomputers;
name "Open Computers";
icon "http://dccg.herokuapp.com/cfproject/223008/avatar";
description "Fix OpenComputers's GUI.";
authors ["Goldenpants21"];
require mod "opencomputers";

color #E3E3E3 -> #575B60;

text transform in li.cil.oc.client.gui.*;
```

**Comment by Zeitheron** [comment]
change icon to ``icon "http://dccg.herokuapp.com/cfproject/223008/avatar";``
add line 2: ``bid b1aadf8b-3f88-4d4c-a0f2-a4a77e9b5fce;``
add line ``require mod "opencomputers";``
