### ISSUE TITLE
Addon to fix for Creative Tab Text

### ISSUE THREAD

**Issue by WenXin20** [Zeitheron/DarkScriptThemes#35]
This fixes the text in creative tabs, making it brighter, unless there is a better way to fix it.
```
version 8;
id default;
name "Default Style";
icon "http://dccg.herokuapp.com/cfproject/323440/avatar";
description "This is the default dark style";
authors ["Zeitheron"];

# Fixes Creative Tab texts for Modded and Vanilla tabs
text transform in net.minecraft.client.gui.*;
```

**Comment by Zeitheron** [comment]
They must have a specific class, not a class range. I'll put it there.

**Comment by Zeitheron** [comment]
Also I don't think this fix is needed since the mod already does texturing to tabs

![image](https://user-images.githubusercontent.com/38943617/60173066-a36c5880-9816-11e9-9297-074187f7eac2.png)

**Comment by Zeitheron** [comment]
Okay, after reloading the texture for a few times this happened. Merging changes.
